2025-05-13 19:55:59,213 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,220 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,226 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,231 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,824 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,839 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,847 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,854 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,862 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,870 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,878 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,885 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,891 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,897 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,902 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,908 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,914 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,920 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,927 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,933 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,938 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,944 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,955 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:24,961 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:25,984 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,004 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,013 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,084 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,099 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,114 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,129 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,139 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,145 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,175 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,185 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,192 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,199 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,206 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,211 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,218 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:56:26,223 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <!-- <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}"> -->
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
