2025-05-13 19:54:43,851 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 18, in template
    <meta property="og:description" content="{% block og_description %}{% block meta_description %}{% endblock %}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateAssertionError: block 'meta_description' defined twice
2025-05-13 19:54:43,858 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 18, in template
    <meta property="og:description" content="{% block og_description %}{% block meta_description %}{% endblock %}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateAssertionError: block 'meta_description' defined twice
2025-05-13 19:54:43,866 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 18, in template
    <meta property="og:description" content="{% block og_description %}{% block meta_description %}{% endblock %}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateAssertionError: block 'meta_description' defined twice
2025-05-13 19:54:43,874 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 18, in template
    <meta property="og:description" content="{% block og_description %}{% block meta_description %}{% endblock %}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateAssertionError: block 'meta_description' defined twice
2025-05-13 19:54:43,882 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 18, in template
    <meta property="og:description" content="{% block og_description %}{% block meta_description %}{% endblock %}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateAssertionError: block 'meta_description' defined twice
2025-05-13 19:55:57,927 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:57,940 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:57,948 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:57,954 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:57,962 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:57,968 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:57,974 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:57,982 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:57,988 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:57,994 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:58,001 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:58,008 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:58,013 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:58,018 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:58,024 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:58,029 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:58,035 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:58,041 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:58,046 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:58,052 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,080 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,100 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,111 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,125 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,136 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,144 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,151 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,157 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,164 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,170 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,176 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,182 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,188 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,194 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,201 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2025-05-13 19:55:59,207 ERROR: Unhandled exception occurred: [in /Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py:1598]
Traceback (most recent call last):
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/app.py", line 1624, in error
    return render_template('error.html', error_message=error, traceback=traceback)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/path/to/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in top-level template code
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanvanderaa/Desktop/Creativity/EkoLinq/Website/templates/base.html", line 24, in block 'og_image'
    <meta property="og:image" content="{% block og_image %}{{ url_for('static','images/social-preview.png') }}{% endblock %}">
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
